language: python
sudo: required

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
  
before_install:
  - sudo apt-get update -qq
  
before_install:
  - pip3 install you-get
  - pip3 install requests
  - pip3 install coverage
install:
  - |
    python3 setup.py build
    python3 setup.py sdist
    python3 setup.py bdist
    python3 setup.py bdist_egg
    python3 setup.py install
    
script:
 - ls
 - cd build
 - ls
 - coverage run setup.py
 - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
