codecov:
  token: 81f6b69e-fc20-4ad5-adb4-34a145ff4db8 
  archive:
    uploads: no
coverage:
  precision: 0
  range: 80...100

comment:
  layout: "header, diff, changes"
coverage:
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/fac1b1e20d99a63a9883"
        threshold: 1%
