name: add submodule

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/assets/
        
        git submodule add git@github.com:lidavidm/sympy-web-static.git static
        
        cd static/
        git init
        ls
        echo '============================================'
        git add -A
        
        git status 
        cd ../../../
        git commit -m "Add Machine Learning Databases "
        ls
        git push origin master


