#you-get -o ./you_get/ -O 16.mp4 'https://huya-w6.huya.com/2023/344519832/yuanhua/e1e19e1747a980581472708c6c1a5c47.mp4'
#you-get -o ./you_get/ -O 18.mp4 'https://huya-w20.huya.com/2023/344540624/yuanhua/561e0e6fab1e21e84b6f2303a04dafad.mp4'
#you-get -o ./you_get/ -o 19.mp4 'https://huya-w6.huya.com/2023/344540624/yuanhua/561e0e6fab1e21e84b6f2303a04dafad.mp4'
#you-get -o ./you_get/ -O 24.mp4 'https://huya-w10.huya.com/2023/344698514/yuanhua/3f52adf2fc1009b55dbff47ebe8a6e1e.mp4'
#you-get -o ./you_get/ -O 28.mp4 'https://huya-w20.huya.com/2023/344697870/yuanhua/343dd8cfeeb2d7194588b578ebfe96ab.mp4'
#you-get -o ./you_get/ -O 32.mp4 'https://huya-w20.huya.com/2023/344702132/yuanhua/f4159e9bb3299222fd5cbb056d6f3329.mp4'
#you-get -o ./you_get/ -O 35.mp4 'https://huya-w6.huya.com/2023/344703440/yuanhua/fe728ae5d72ad4e4f776fbdf95bbe641.mp4'
#you-get -o ./you_get/ -O 37.mp4 'https://huya-w10.huya.com/2023/344704526/yuanhua/1a0ef8272ff0a88f88e75aa5558c3cfc.mp4'
#you-get -o ./you_get/ -O 39.mp4 'https://huya-w21.huya.com/2023/344705390/yuanhua/4d217cafc61ad5a6a9dd0d60f5a89af5.mp4'
#you-get -o ./you_get/ -O 41.mp4 'https://huya-w21.huya.com/2023/344706782/yuanhua/a4e0e6968160c912c054ca7d87a16cb2.mp4'
name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls 
        echo "=========================="
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ -O 16 'https://huya-w20.huya.com/2023/344519832/1300/69b7a6dc3f0ef03b98afbb7d2436a37a.mp4'
        you-get -o ./you_get/ -O 18 'https://huya-w20.huya.com/2023/344540624/350/54ef0a3d4adc63728d915321855f439e.mp4'
                                        
        you-get -o ./you_get/ -o 19 'https://huya-w10.huya.com/2023/344542000/1300/61abcc2085f727adc89e473fd82eaab8.mp4'
        you-get -o ./you_get/ -O 24 'https://huya-w6.huya.com/2023/344697142/350/32b6a0676aa61c5968444802948f5349.mp4'
        you-get -o ./you_get/ -O 28 'https://huya-w20.huya.com/2023/344697870/1300/edb758a3ae18f0ec9fd7e9d965ebb96f.mp4'
        you-get -o ./you_get/ -O 32 'https://huya-w20.huya.com/2023/344702132/1300/8e7b5c6bd51aff67bacd20f41a510635.mp4'
        you-get -o ./you_get/ -O 35 'https://huya-w10.huya.com/2023/344703440/1300/aed2262d73ce9ab15e034f3c741e3787.mp4'
        you-get -o ./you_get/ -O 37 'https://huya-w10.huya.com/2023/344704526/1300/12205af3079d849422f1bdb37f6481f3.mp4'
        you-get -o ./you_get/ -O 39 'https://huya-w6.huya.com/2023/344705390/1300/7e4c57b85f92dc1ad14a5aa74e976607.mp4'
        you-get -o ./you_get/ -O 41 'https://huya-w21.huya.com/2023/344706782/1300/94a25cdc4ab4fa41641cab128a34dcd0.mp4'
        
        ls
        echo '============================================='
        cd you_get
        ls
        echo '=========================================='
        
        cd ../
        
        #mkdir Python-videos-for-beginners/source/assets/videos/PythonIntro
        
        cp -r you_get/. Python-videos-for-beginners/source/assets/videos/PythonIntro/
        cd Python-videos-for-beginners/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/assets/videos/PythonIntro/
        git add -A
        git status 
        cd ../../../../
        git commit -m "Add some videos"
        ls
        git push origin master
