name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        ls
        echo '============================================'
        
        git rm -rf python4everybody
        git commit -m "remove all the pics"
        
        mkdir python4everybody
        cd python4everybody/
        echo "show python 2 version"
        python -v
        echo "-----------------------------------------"
        echo "show python 3 version"
        python3 -v 
        echo "-------------------------------------------"
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/Python-videos-for-beginners/Python-videos-for-beginners/source/assets/images/python4everybody"
        pip3 install PyMuPDF
        ls -lt
        pwd
        echo "running mupdf......"
        python3 pdf2png.py
        ls -lt
        
        wget -O python4all.zip https://yozonetdisk.obs.cn-east-2.myhuaweicloud.com/document/83fda760b27742b1aa9daa79ee752eb4/babel.zip?AccessKeyId=UF740COJY9EEWPIMZOMU&Expires=1600913957&response-content-disposition=attachment%3B+filename%3D%22pythonlearn.zip%22%3Bfilename*%3DUTF-8%27%27pythonlearn.zip&Signature=kh7w86NxGFEIYucmVHj9f8FrjE0%3D
        unzip python4all.zip
        git rm -f python4all.zip
        git commit -m "delete zip"
        git add -A
        git commit -m "add some photos"
        
        cd ../../../../
        git commit -m "Add some videos"
        ls
        git push origin master     
