name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/py4bslides/
        
        ls
        echo '============================================'
        
        mkdir NumericVariables
        cd NumericVariables/
        wget -O NumericVariables.zip https://onlineconvertfree.com/upload/converter/030920/7e5nCvc/5_-_NumericVariables.zip
        unzip NumericVariables.zip
        git add -A
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
