name: Upload Machine Learning Bases

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/py4bslides/Intro/
        ls
        echo '============================================'

        wget -O Intro0.jpg http://docpe.com/Download/090217201087_00-Intro_0.jpg
        wget -O Intro1.jpg http://docpe.com/Download/090217201087_00-Intro_1.jpg
        wget -O Intro2.jpg http://docpe.com/Download/090217201087_00-Intro_2.jpg
        wget -O Intro3.jpg http://docpe.com/Download/090217201087_00-Intro_3.jpg
        wget -O Intro4.jpg http://docpe.com/Download/090217201087_00-Intro_4.jpg
        wget -O Intro5.jpg http://docpe.com/Download/090217201087_00-Intro_5.jpg
        wget -O Intro6.jpg http://docpe.com/Download/090217201087_00-Intro_6.jpg
        wget -O Intro7.jpg http://docpe.com/Download/090217201087_00-Intro_7.jpg


        git add -A
        
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
