name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/evenmopy4b/
        
        ls
        echo '============================================'
        
        mkdir CSV_Files_and_Jupyter_notebooks
        cd CSV_Files_and_Jupyter_notebooks/
        wget -O ErrorHandling.zip https://onlineconvertfree.com/upload/converter/030920/c4was8X/6_-_CSV_Files_and_Jupyter_notebooks.zip
        unzip ErrorHandling.zip
        git add -A
        git rm -f ErrorHandling.zip
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
