name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        ls
        echo '============================================'
        
        cd python4everybody/
        python -v
        wget https://files.pythonhosted.org/packages/ca/5e/398dc7e149dec951bdcb67c5d350860a37d6bbfeac9640ee017cb4dfbb5c/PyMuPDF-1.17.7-cp37-cp37m-macosx_10_9_x86_64.whl
        pip3 install PyMuPDF-1.17.7-cp37-cp37m-macosx_10_9_x86_64.whl
        ls -lt
        pwd
