name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/evenmopy4b/
        
        ls
        echo '============================================'
        
        mkdir Working_with_numpy_and_pandas
        cd Working_with_numpy_and_pandas/
        wget -O ErrorHandling.zip https://onlineconvertfree.com/upload/converter/030920/08tyIww/14_-_Working_with_numpy_and_pandas.zip
        unzip ErrorHandling.zip
        git add -A
        git rm -f ErrorHandling.zip
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
