name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-20.04
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        mkdir pymupdf
        cd pymupdf/
        ls
        echo '============================================'
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/Python-videos-for-beginners/Python-videos-for-beginners/source/assets/images/pymupdf"
        wget -O PyMuPDF-1.17.7-cp36-cp36m-manylinux2010_x86_64.whl https://files.pythonhosted.org/packages/3e/26/14e9a0ae8c7c831af95bc7879a562cec8b5d297dc8febf50145b54b1571b/PyMuPDF-1.17.7-cp36-cp36m-manylinux2010_x86_64.whl
        pip3 install PyMuPDF-1.17.7-cp36-cp36m-manylinux2010_x86_64.whl
        
        cd ../../../../
        ls
        git push origin master     
