name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/mopy4bslides/
        
        ls
        echo '============================================'
        
        mkdir Working_with_files
        cd Working_with_files/
        wget -O Working_with_files.zip https://onlineconvertfree.com/upload/converter/030920/eOnklsa/07_-_Working_with_files.zip
        unzip Working_with_files.zip
        git add -A
        git rm -f Working_with_files.zip
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
