name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        ls
        echo '============================================'
        
        cd python4everybody/
        echo "show python 2 version"
        python -v
        echo "-----------------------------------------"
        echo "show python 3 version"
        python3 -v 
        echo "-------------------------------------------"
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/Python-videos-for-beginners/"
        pip3 install PyMuPDF
        ls -lt
        pwd
        echo "running mupdf......"
        python3 pdf2png.py
        ls -lt
        
        
        
