name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        ls
        echo '============================================'
        
        cd python4everybody/
        echo "show python 2 version"
        python -v
        echo "-----------------------------------------"
        echo "show python 3 version"
        python3 -v
        wget https://files.pythonhosted.org/packages/bd/50/2cb160109ad1a93d75880eb0c438941bcabcc6bc38f3747c048be67498f6/PyMuPDF-1.17.7-cp27-cp27mu-manylinux2010_x86_64.whl
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/Python-videos-for-beginners/"
        pip install PyMuPDF-1.17.7-cp27-cp27mu-manylinux2010_x86_64.whl
        ls -lt
        pwd
        echo "running mupdf......"
        python pdf2png.py
        ls -lt
        
