name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/mopy4bslides/
        
        ls
        echo '============================================'
        
        mkdir Formatting_and_linting
        cd Formatting_and_linting/
        wget -O Formatting_and_linting.zip https://onlineconvertfree.com/upload/converter/030920/TvQLwJ6/01_-_Formatting_and_linting.zip
        unzip Formatting_and_linting.zip
        git add -A
        git rm -f Formatting_and_linting.zip
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
