name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/mopy4bslides/
        
        ls
        echo '============================================'
        
        mkdir Managing_the_file_system
        cd Managing_the_file_system/
        wget -O Managing_the_file_system.zip https://onlineconvertfree.com/upload/converter/030920/OZfMnpd/06_-_Managing_the_file_system.zip
        unzip Managing_the_file_system.zip
        git add -A
        git rm -f Managing_the_file_system.zip
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
