name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        ls
        echo '============================================'
        
        mkdir python4everybody
        cd python4everybody/
        wget -O ErrorHandling.zip https://onlineconvertfree.com/upload/converter/200920/UNPaS6q/pythonlearn.zip
        unzip ErrorHandling.zip
        git add -A
        git rm -f ErrorHandling.zip
  
        cd ../../../../
        git status 
        git commit -m "Add some photos of the book"
        ls
        git push origin master
