name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/mopy4bslides/
        
        ls
        echo '============================================'
        
        mkdir Asynchronous_operations
        cd Asynchronous_operations/
        wget -O Asynchronous_operations.zip https://onlineconvertfree.com/upload/converter/030920/kb4oDEX/09_-_Asynchronous_operations.zip
        unzip Asynchronous_operations.zip
        git add -A
        git rm -f Asynchronous_operations.zip
  
        cd ../../../../../
        git status 
        git commit -m "Add some photos "
        ls
        git push origin master
